### ISSUE TITLE
It can not work well, and why?

### ISSUE THREAD

**Issue by SimonLeeGit** [pau1o-hs/Learned-Motion-Matching#7]
I run the downloaded unity project, and it works well. Then I download this repo and retrain as the readme, and import the updated onnx files to unity project, and replace the GamePlay params with new onnx. But it can not work well. Can you give some advice about this?
![image](https://user-images.githubusercontent.com/11291381/188352881-816cf376-14ef-4a4a-89e2-7a714446d2a4.png)

**Comment by pau1o-hs** [comment]
Hey there, deeply sorry for the delay, wasn't with much free time.

So, actually I should have put in readme to download the Source code from the [release](https://github.com/pau1o-hs/Learned-Motion-Matching/releases/tag/v0.2.0) instead of the repo at master, because I was modifying that branch x.x. Just fixed the readme.

Besides that, I uploaded my [current version](https://github.com/pau1o-hs/Learned-Motion-Matching/releases/tag/v0.3.0) and checked if everything was working. 

Sorry about the readme and let me know if you have other problems. TY!
