### ISSUE TITLE
Having a trouble with running the unity sample.

### ISSUE THREAD

**Issue by daqjjang** [pau1o-hs/Learned-Motion-Matching#9]
Hi, nice work with the learned motion matching~
I tried to load unity sample and I've got this error. 
What process should I do?

![image](https://user-images.githubusercontent.com/12400318/209750483-4ba350e2-cd0c-4eb4-a7f9-db76338976ee.png)

**Comment by wasimjj** [comment]
> Hi, nice work with the learned motion matching~ I tried to load unity sample and I've got this error. What process should I do?
> 
> ![image](https://user-images.githubusercontent.com/12400318/209750483-4ba350e2-cd0c-4eb4-a7f9-db76338976ee.png)

I was having the same problem , it's because in code valued are divided by zero. Replace attached file code and your error should be fixed.   
[Motion Matching.docx](https://github.com/pau1o-hs/Learned-Motion-Matching/files/10312758/Motion.Matching.docx)

But I am stuck in next issue unity not able handle float values. when try to play character disappear.  
![Screenshot 2022-12-28 122150](https://user-images.githubusercontent.com/5476728/209774465-20f35d3f-052f-4ce4-9469-a620abc03555.png)

![Screenshot 2022-12-28 122222](https://user-images.githubusercontent.com/5476728/209774482-dce51fa6-0359-42af-a765-27fb5dc4fd3d.png)

I think its because of too much values after precision point.

**Comment by mrtariqkhan** [comment]
@pau1o-hs I am having the same issue with precision point mentioned by @wasimjj. We are on Cuda version 12. Please guide.

**Comment by pau1o-hs** [comment]
> Hi, nice work with the learned motion matching~ I tried to load unity sample and I've got this error. What process should I do?

Hey, thanks a lot!

So I just downloaded lmm-v0.3.0.zip from the release tag, hit play and it's working fine. Did you do anything beyond that?

**Comment by pau1o-hs** [comment]
@wasimjj Thanks for your help! 

I see you changed everything from float to double in the code, right? But as I said, I just downloaded the demo and it's working for me. Maybe it's a problem about systems architectures? I don't know yet.

I used to have these problems with "NaN" and "Screen Position out of view frustum" when my NN (neural network) outputs were really bad and threw the character too far away from the world.

I'll look around, but it's difficult when I'm not facing the problem :S

**Comment by wasimjj** [comment]
@pau1o-hs  yes changed this float to double but its same with out this change. I just downloaded your unity project Imm-v0.3.0 and played without changes. I got the errors infinite and NaN values.

that was because some vectors and array values was divided by zero.  Yes you are right it could be architecture issue. can you suggest how we can solve this ? may we can arrange call on Discord or some where.  

Unity version is :2021.3.11f1 
windows 11 .

Cuda 
nvcc: NVIDIA (R) Cuda compiler driver
Copyright (c) 2005-2022 NVIDIA Corporation
Built on Mon_Oct_24_19:40:05_Pacific_Daylight_Time_2022
Cuda compilation tools, release 12.0, V12.0.76
Build cuda_12.0.r12.0/compiler.31968024_0

python
Python 3.10.9 (tags/v3.10.9:1dd9be6, Dec  6 2022, 20:01:21) [MSC v.1934 64 bit (AMD64)] on win32
Type "help", "copyright", "credits" or "license" for more information.

**Comment by pau1o-hs** [comment]
https://discord.gg/dzQbhBzs

**Comment by pau1o-hs** [comment]
Hey lads, just found the problem, in Brazil we use comma for floating values haha. For while, just replace line 738 from MotionMatching.cs for: 

```
foreach (var _item in line.Split(' ').ToList())
``` 

If you get any other problem please let me know, thanks :)

**Comment by daqjjang** [comment]
> Hey lads, just found the problem, in Brazil we use comma for floating values haha. For while, just replace line 738 from MotionMatching.cs for:
> 
> ```
> foreach (var _item in line.Split(' ').ToList())
> ```
> 
> If you get any other problem please let me know, thanks :)

**Comment by daqjjang** [comment]
Wow, I just closed the issue by mistake. Anyway, thanks for the help, you guys!
That is a pretty simple solution, haha. 
I will modify the code and test it right away!

**Comment by daqjjang** [comment]
It is working~~ Thanks!!
